language: php
php:
  - "5.6"
  - "7.0"

install:
  - composer install

script:
  - phpunit --whitelist src/ --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
