language: php

php:
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"
  - "7.3"

services:
  - mysql

env:
  jobs:
    - BITRIX=v18.5
    - BITRIX=v19.0
  global:
    - MYSQL_HOST=127.0.0.1
    - MYSQL_DATABASE=bitrix
    - MYSQL_USER=root
    - MYSQL_PASSWORD=

before_install:
  - mysql -e 'CREATE DATABASE bitrix;'

install:
  - composer install --no-interaction

before_script:
  - echo 'short_open_tag = 1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'mbstring.func_overload = 2' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - composer require --dev sheerockoff/bitrix-ci:$BITRIX
  - php vendor/bin/phpunit --whitelist src/ --coverage-text --coverage-clover clover.xml

after_script:
  - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./cc-test-reporter after-build -t clover; fi
